apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ssco-ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
  name: ibm-spectrum-scale-csi-operator
  namespace: ibm-spectrum-scale-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ssco-external-attacher-runner
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
  name: ibm-spectrum-scale-csi-attacher
  namespace: ibm-spectrum-scale-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ssco-csi-nodeplugin
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
  name: ibm-spectrum-scale-csi-node
  namespace: ibm-spectrum-scale-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ssco-external-provisioner-runner
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
  name: ibm-spectrum-scale-csi-provisioner
  namespace: ibm-spectrum-scale-csi-driver
